name: Feature Request
description: 새로운 기능 제안을 작성해주세요
title: "[Feature] "
labels: ["Feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: 기능 설명
      placeholder: 어떤 기능을 원하시나요?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 필요성
      placeholder: 이 기능이 필요한 이유를 설명해주세요
    validations:
      required: false

