name: Refactor
description: 리팩토링 제안을 작성해주세요
title: "[Refactor] "
labels: ["Refactor"]
body:
  - type: textarea
    id: description
    attributes:
      label: 리팩토링 설명
      placeholder: 어떤 코드를 리팩토링하고 싶은지 설명해주세요
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 리팩토링 이유
      placeholder: 리팩토링이 필요한 이유를 설명해주세요
    validations:
      required: false

